/**
 * Thesis figure capture. Not a test: it drives the real platform and writes the
 * screenshots the thesis reproduces, so they are regenerable like every other
 * figure rather than being ad-hoc binaries with no source.
 *
 * The five screenshots currently in `docs/thesis/figures` were captured by hand
 * in September 2026, before the geometric facial channel replaced the pixel one,
 * and nothing in the repository could reproduce them. Every other figure in the
 * document is generated by a committed script; these were the exception, and the
 * thesis argues in Section 7.4 that an artefact with no generator is
 * indistinguishable from one whose output is stale. This closes that gap.
 *
 * Run against a populated instance, not a bare one. The admin panels render what
 * the session actually produced, so a run with no cycles behind it captures
 * empty states:
 *
 *   FIGURES=1 npx playwright test figures --project=chromium
 *
 * Without FIGURES=1 the file is skipped, so it never runs in CI: it writes
 * outside the test tree and depends on real detector output, both of which a
 * CI run should not do.
 *
 * Output goes to docs/thesis/figures with the filenames the chapter sources
 * already reference. A capture that cannot reach its target state fails loudly
 * rather than writing a misleading image, because a screenshot of the wrong
 * state is worse than a missing one: `check_submission.py` catches the second.
 */

import { test, expect, type Page } from "@playwright/test";
import path from "node:path";
import {
  apiEnroll,
  apiGetMe,
  apiGiveConsent,
  apiRegister,
  apiSetWebcamMode,
  getCourseDetail,
  getFirstCourseId,
  loginAsAdmin,
  loginAsDesigner,
  makeCredentials,
  seedSessionStorage,
} from "./helpers/auth";

const FIGURES = path.resolve(
  __dirname,
  "..",
  "..",
  "..",
  "docs",
  "thesis",
  "figures",
);

// One 30-second affect cycle, plus slack for the agent graph to run and the
// monitor's SSE stream to deliver the result. Six cycles is the session cap, so
// the aggregate and lifecycle panels need roughly that many to show anything.
const CYCLE_MS = 30_000;
const SETTLE_MS = 4_000;

test.describe.configure({ mode: "serial", timeout: 15 * 60_000 });

test.skip(!process.env.FIGURES, "set FIGURES=1 to capture thesis figures");

test.use({
  viewport: { width: 1440, height: 900 },
  deviceScaleFactor: 2, // the document scales figures to 4.5in; 1x reads as mush in print
  launchOptions: {
    args: [
      "--use-fake-ui-for-media-stream",
      // A synthetic source, so no person's image appears in the thesis. The
      // existing webcam figure notes this and the note has to stay true.
      "--use-fake-device-for-media-stream",
    ],
  },
  permissions: ["camera"],
});

/** Write one whole-viewport figure. */
async function shot(page: Page, name: string) {
  await page.screenshot({ path: path.join(FIGURES, name), fullPage: false });
  console.log(`  wrote ${name}`);
}

/** A panel is only worth capturing once it has rendered real content. */
async function panel(page: Page, heading: RegExp, name: string) {
  const region = page
    .locator("section, article, div")
    .filter({ has: page.getByRole("heading", { name: heading }) })
    .first();
  await expect(region).toBeVisible({ timeout: 30_000 });
  await expect(region).not.toContainText(/no data yet|not recorded yet/i);
  await region.screenshot({ path: path.join(FIGURES, name) });
  console.log(`  wrote ${name}`);
}

// ---------------------------------------------------------------------------
// 1 and 2: the consent and webcam steps (Figures 3.14 and 3.15)
// ---------------------------------------------------------------------------
// Both predate the geometry commit, which rewrote the consent copy from "no
// video is stored" to "no image is transmitted". The captures have to be redone
// or the thesis reproduces a promise the platform no longer makes.

test("onboarding consent and webcam steps", async ({ page, request }) => {
  const creds = makeCredentials("figures-onboarding");
  const tokens = await apiRegister(request, creds);
  const user = await apiGetMe(request, tokens.accessToken);
  await seedSessionStorage(page, tokens, user);

  await page.goto("/onboarding");
  await page.getByRole("button", { name: /get started|continue|next/i }).first().click();

  await expect(page.getByRole("heading", { name: /consent/i })).toBeVisible();
  await expect(page.getByText(/never leaves|no image|not transmitted/i)).toBeVisible();
  await shot(page, "figshot-consent.png");

  await page.getByRole("checkbox").first().check();
  await page.getByRole("button", { name: /agree|continue|next/i }).first().click();

  await expect(page.getByRole("heading", { name: /webcam|camera/i })).toBeVisible();
  await shot(page, "figshot-webcam.png");
});

// ---------------------------------------------------------------------------
// 3 to 8: one live learner session, captured from both sides
// ---------------------------------------------------------------------------
// The learner-side and admin-side captures must come from the SAME session, or
// the monitor figures show numbers the lesson figure cannot account for. Two
// contexts share one browser so both are open simultaneously.

test("live session, learner side and pipeline monitor", async ({ browser, request }) => {
  const learnerCtx = await browser.newContext({
    viewport: { width: 1440, height: 900 },
    permissions: ["camera"],
  });
  const adminCtx = await browser.newContext({ viewport: { width: 1600, height: 1000 } });
  const learner = await learnerCtx.newPage();
  const admin = await adminCtx.newPage();

  // Consent and webcam mode are set through the API rather than the wizard, so
  // this capture does not depend on the onboarding figures above passing first.
  const creds = makeCredentials("figures-session");
  const tokens = await apiRegister(request, creds);
  await apiGiveConsent(request, tokens.accessToken);
  await apiSetWebcamMode(request, tokens.accessToken, true);
  const user = await apiGetMe(request, tokens.accessToken);
  await seedSessionStorage(learner, tokens, user);

  const courseId = await getFirstCourseId(request, tokens.accessToken);
  await apiEnroll(request, tokens.accessToken, courseId);
  const detail = await getCourseDetail(request, tokens.accessToken, courseId);
  const moduleId = detail.modules[0].id;
  const lessonId = detail.modules[0].lessons[0].id;

  await loginAsAdmin(request, admin);
  await admin.goto("/monitor");

  await learner.goto(
    `/courses/${courseId}/modules/${moduleId}/lessons/${lessonId}`,
  );
  // The indicator is the learner's only view of the detection state, so its
  // presence is what makes the lesson capture evidence of an adaptive session.
  await expect(learner.getByText(/adaptive mode active/i)).toBeVisible({
    timeout: 60_000,
  });

  // Pick up the session the learner just opened, so the two sides agree.
  await admin.reload();
  const picker = admin.getByRole("combobox").first();
  if (await picker.isVisible().catch(() => false)) {
    await picker.selectOption({ index: 1 });
  }

  // The config banner is the single most load-bearing capture in the set: it is
  // what shows the facial channel is the geometric one and which floors apply.
  await expect(admin.getByText(/facial:\s*geometry/i)).toBeVisible({
    timeout: 60_000,
  });
  await shot(admin, "figshot-monitor-config.png");

  // Let the session accumulate cycles. Six is the per-session offer cap, so it
  // is also the point at which the aggregate panels have something to show.
  for (let cycle = 1; cycle <= 6; cycle += 1) {
    await learner.waitForTimeout(CYCLE_MS);
    // Reading and navigating is what produces behavioural and performance
    // signal; a static page yields the near-inert window Section 4.12 reports.
    await learner.mouse.move(300 + cycle * 40, 300 + cycle * 20);
    await learner.mouse.wheel(0, 400);
    const next = learner.getByRole("button", { name: /next/i }).first();
    if (await next.isEnabled().catch(() => false)) await next.click();
  }
  await admin.waitForTimeout(SETTLE_MS);

  await shot(learner, "figshot-lesson.png");
  await panel(admin, /current detection/i, "figshot-monitor-detection.png");
  await panel(admin, /facial/i, "figshot-monitor-facial.png");
  await panel(admin, /detection timeline/i, "figshot-monitor-timeline.png");
  await panel(admin, /intervention/i, "figshot-monitor-interventions.png");
  await shot(admin, "figshot-monitor.png");

  await admin.getByRole("tab", { name: /aggregate/i }).click();
  await expect(admin.getByText(/why cycles did not adapt/i)).toBeVisible({
    timeout: 30_000,
  });
  await shot(admin, "figshot-monitor-aggregate.png");

  await learnerCtx.close();
  await adminCtx.close();
});

// ---------------------------------------------------------------------------
// 9: system health, which is what proves which artefact is loaded
// ---------------------------------------------------------------------------

test("system health, models and gate configuration", async ({ page, request }) => {
  await loginAsAdmin(request, page);
  await page.goto("/system-health");
  await expect(page.getByText(/engagenet_lean_gbdt/i)).toBeVisible({
    timeout: 30_000,
  });
  // Section 4.12 reports the behavioural artefact as the DUX gradient-boosted
  // tree. If the instance has loaded the synthetic Bi-LSTM instead, the figure
  // would put a non-reportable model into the thesis, so the capture refuses.
  await expect(page.getByText(/behavioral_bilstm/i)).toHaveCount(0);
  await shot(page, "figshot-system-health.png");
});

// ---------------------------------------------------------------------------
// 10 and 11: the course-designer affect view and its section drill-down
// ---------------------------------------------------------------------------

test("designer affect heatmap and section drill-down", async ({ page, request }) => {
  const { tokens } = await loginAsDesigner(request, page);
  const courseId = await getFirstCourseId(request, tokens.accessToken);

  await page.goto(`/analytics/${courseId}`);
  await expect(page.getByRole("grid")).toBeVisible({ timeout: 30_000 });
  await shot(page, "figshot-heatmap.png");

  const firstSection = page.getByRole("row").nth(1);
  if (await firstSection.isVisible().catch(() => false)) {
    await firstSection.click();
    await expect(page.getByText(/affect distribution/i)).toBeVisible({
      timeout: 30_000,
    });
    await shot(page, "figshot-section-detail.png");
  }
});
