/**
 * TypeScript/Python parity for per-frame facial geometry.
 *
 * The fixture is generated by running `extract_geometry.py`'s own functions over synthetic
 * landmarks, so these assertions compare this file against the code that produced the training
 * data — not against a second implementation of the same idea.
 *
 * What this CAN settle: every formula. Euler decomposition, eye aspect ratio, the gaze proxy,
 * mouth openness, motion energy, and the NaN discipline.
 *
 * What it CANNOT settle: the layout MediaPipe hands back its 4x4 matrix in. That depends on the
 * runtime, not on arithmetic, so `toRowMajor`'s `transpose` default is verified in a browser (see
 * the note on that function) rather than here.
 */

import { describe, expect, it } from "vitest";

import fixture from "./__fixtures__/geometry-parity.json";
import {
  GEOMETRY_CHANNEL_ORDER,
  GEOMETRY_CONTRACT,
  eulerFromMatrix,
  eyeAspectRatio,
  frameGeometry,
  gazeProxy,
  geometryToWire,
  motionEnergy,
  mouthOpenness,
  toRowMajor,
  type Landmark,
} from "./geometry";

const EYE_L = [33, 160, 158, 133, 153, 144];
const EYE_R = [362, 385, 387, 263, 373, 380];
const TOL = 1e-9;

type Case = {
  landmarks: number[][];
  prev: number[][];
  matrixRowMajor: number[];
  expected: Record<string, number>;
};

const toLandmarks = (rows: number[][]): Landmark[] =>
  rows.map(([x, y, z]) => ({ x, y, z }));

const cases = fixture.cases as Case[];

describe("geometry parity with the training extractor", () => {
  it("has cases to check", () => {
    expect(cases.length).toBeGreaterThan(0);
  });

  it.each(cases.map((c, i) => [i, c] as const))(
    "case %i reproduces every channel",
    (_i, c) => {
      const pts = toLandmarks(c.landmarks);
      const prev = toLandmarks(c.prev);
      const [yaw, pitch, roll] = eulerFromMatrix(c.matrixRowMajor);

      expect(yaw).toBeCloseTo(c.expected.yaw, 9);
      expect(pitch).toBeCloseTo(c.expected.pitch, 9);
      expect(roll).toBeCloseTo(c.expected.roll, 9);

      expect(eyeAspectRatio(pts, EYE_L)).toBeCloseTo(c.expected.ear_l, 9);
      expect(eyeAspectRatio(pts, EYE_R)).toBeCloseTo(c.expected.ear_r, 9);
      expect(mouthOpenness(pts)).toBeCloseTo(c.expected.mouth_open, 9);

      const [gx, gy] = gazeProxy(pts);
      expect(gx).toBeCloseTo(c.expected.gaze_x, 9);
      expect(gy).toBeCloseTo(c.expected.gaze_y, 9);

      expect(motionEnergy(pts, prev)).toBeCloseTo(c.expected.motion, 9);
    },
  );

  it("assembles the full row in the contract's channel order", () => {
    const c = cases[0];
    const row = frameGeometry(
      toLandmarks(c.landmarks),
      c.matrixRowMajor,
      toLandmarks(c.prev),
    );
    expect(row).toHaveLength(GEOMETRY_CHANNEL_ORDER.length);
    for (const ch of ["yaw", "pitch", "roll", "ear_l", "ear_r", "ear_mean",
                      "mouth_open", "gaze_x", "gaze_y", "motion"] as const) {
      expect(row[GEOMETRY_CHANNEL_ORDER.indexOf(ch)]).toBeCloseTo(c.expected[ch], 9);
    }
    expect(row[GEOMETRY_CHANNEL_ORDER.indexOf("face_found")]).toBe(1);
  });
});

describe("missing faces", () => {
  it("emits NaN, never zero, so aggregation excludes the frame", () => {
    const row = frameGeometry(null, null, null);
    const foundIdx = GEOMETRY_CHANNEL_ORDER.indexOf("face_found");
    row.forEach((v, i) => {
      if (i === foundIdx) expect(v).toBe(0);
      else expect(Number.isNaN(v)).toBe(true);
    });
  });

  it("does not report motion on the first frame of a cycle", () => {
    // No previous frame means no displacement to measure. Zero would read as "perfectly still".
    expect(Number.isNaN(motionEnergy(toLandmarks(cases[0].landmarks), null))).toBe(true);
  });

  it("survives JSON serialisation without NaN becoming 0", () => {
    // JSON.stringify turns NaN into null; a coercion to 0 here would record "looking straight
    // ahead" at exactly the moment a learner looked away.
    const wire = geometryToWire([frameGeometry(null, null, null)]);
    const round = JSON.parse(JSON.stringify(wire)) as (number | null)[][];
    expect(round[0][GEOMETRY_CHANNEL_ORDER.indexOf("gaze_x")]).toBeNull();
    expect(round[0][GEOMETRY_CHANNEL_ORDER.indexOf("face_found")]).toBe(0);
  });
});

describe("matrix layout", () => {
  it("transposes by default, and the two layouts genuinely differ", () => {
    const rowMajor = cases[0].matrixRowMajor;
    // Feed it as if it had arrived column-major: toRowMajor should undo that.
    const asColumnMajor = new Array<number>(16);
    for (let i = 0; i < 4; i += 1) {
      for (let j = 0; j < 4; j += 1) asColumnMajor[j * 4 + i] = rowMajor[i * 4 + j];
    }
    expect(toRowMajor(asColumnMajor)).toEqual(rowMajor);
    expect(toRowMajor(asColumnMajor, false)).not.toEqual(rowMajor);

    // And the choice is not cosmetic: a transposed matrix yields different angles.
    const a = eulerFromMatrix(rowMajor);
    const b = eulerFromMatrix(asColumnMajor);
    expect(Math.abs(a[0] - b[0]) + Math.abs(a[1] - b[1])).toBeGreaterThan(TOL);
  });

  it("accepts MediaPipe's { data } shape", () => {
    expect(toRowMajor({ data: cases[0].matrixRowMajor }, false)).toEqual(
      cases[0].matrixRowMajor,
    );
  });
});

describe("the frame-spacing contract", () => {
  it("pins 10 frames at 1 fps", () => {
    // The constant that drifted unnoticed on the pixel path (trained 1.93 s, served 0.67 s).
    expect(GEOMETRY_CONTRACT.framesPerCycle).toBe(10);
    expect(GEOMETRY_CONTRACT.captureFps).toBe(1);
    expect(GEOMETRY_CONTRACT.nChannels).toBe(11);
  });
});
