/**
 * Train/serve preprocessing PARITY — the test that did not exist, and whose absence let the
 * deployed facial model be fed the wrong crop geometry for its entire life.
 *
 * `preprocess.test.ts` checks the TS implementation against hardcoded expectations, so it would
 * have passed unchanged while the training pipeline used a completely different cropper — which is
 * exactly what happened. This file instead pins the geometry against a fixture generated by the
 * PYTHON reference (`affectlearn-ml/evaluation/crop_gap_eval.py::_haar_crop`, which is what the
 * uncommitted `crops_mp.py` replicated).
 *
 * The fixture deliberately uses nearest-neighbour sampling: canvas `drawImage` and
 * `cv2.INTER_LINEAR` use different filter kernels, and the thing worth pinning is the geometry and
 * normalisation, not the interpolation kernel. So `padBox` is asserted exactly, and the pixel
 * pipeline is asserted through `normalizeRgbaToChwFloat32`, which has no resampling in it.
 */

import { describe, it, expect } from "vitest";
import fixture from "./__fixtures__/crop-parity.json";
import {
  PREPROCESS_CONTRACT,
  centerCropBox,
  largestBox,
  normalizeRgbaToChwFloat32,
  padBox,
} from "./preprocess";

describe("crop geometry parity with the training reference", () => {
  it("pads the box by 10% on each side, matching the Python reference exactly", () => {
    const got = padBox(fixture.bbox, fixture.frame);
    const want = fixture.expectedPaddedBox;
    expect(got.originX).toBeCloseTo(want.originX, 6);
    expect(got.originY).toBeCloseTo(want.originY, 6);
    expect(got.width).toBeCloseTo(want.width, 6);
    expect(got.height).toBeCloseTo(want.height, 6);
  });

  it("declares the padding fraction in the contract, so it cannot drift silently again", () => {
    expect(PREPROCESS_CONTRACT.boxPadFraction).toBe(0.1);
    expect(PREPROCESS_CONTRACT.faceSelection).toBe("largest");
    expect(PREPROCESS_CONTRACT.facelessFallback).toBe("center_crop");
  });

  it("clamps the padded box to the frame instead of reading outside it", () => {
    // A box flush against the top-left: padding must not produce negative origins.
    const b = padBox({ originX: 0, originY: 0, width: 10, height: 10 }, { width: 40, height: 30 });
    expect(b.originX).toBe(0);
    expect(b.originY).toBe(0);

    // A box flush against the bottom-right: must not exceed the frame.
    const c = padBox(
      { originX: 30, originY: 20, width: 10, height: 10 },
      { width: 40, height: 30 },
    );
    expect(c.originX + c.width).toBeLessThanOrEqual(40);
    expect(c.originY + c.height).toBeLessThanOrEqual(30);
  });

  it("expands area by ~1.44x when unclamped — the ratio that was missing in production", () => {
    const raw = { originX: 100, originY: 100, width: 50, height: 40 };
    const padded = padBox(raw, { width: 1000, height: 1000 });
    const ratio = (padded.width * padded.height) / (raw.width * raw.height);
    expect(ratio).toBeCloseTo(1.44, 2);
  });
});

describe("face selection", () => {
  it("picks the largest detection by area, not the first returned", () => {
    const boxes = [
      { originX: 0, originY: 0, width: 10, height: 10 }, // first, but small
      { originX: 50, originY: 50, width: 40, height: 30 }, // largest
      { originX: 5, originY: 5, width: 20, height: 20 },
    ];
    expect(largestBox(boxes)).toBe(boxes[1]);
  });

  it("returns undefined for no detections, so the caller can centre-crop", () => {
    expect(largestBox([])).toBeUndefined();
  });
});

describe("faceless fallback", () => {
  it("produces the largest centred square, matching the reference fallback", () => {
    // Landscape: square is limited by height, centred horizontally.
    expect(centerCropBox({ width: 40, height: 30 })).toEqual({
      originX: 5,
      originY: 0,
      width: 30,
      height: 30,
    });
    // Portrait: limited by width, centred vertically.
    expect(centerCropBox({ width: 30, height: 40 })).toEqual({
      originX: 0,
      originY: 5,
      width: 30,
      height: 30,
    });
    // Already square: identity.
    expect(centerCropBox({ width: 96, height: 96 })).toEqual({
      originX: 0,
      originY: 0,
      width: 96,
      height: 96,
    });
  });
});

describe("normalisation parity", () => {
  it("reproduces the Python reference's ImageNet CHW values", () => {
    // Rebuild the fixture's sampling in TS: same nearest-neighbour walk over the padded box,
    // then the shared normalisation. This isolates geometry+normalisation from resampling.
    const { width: W, height: H } = fixture.frame;
    const size = PREPROCESS_CONTRACT.cropSize;

    // Same synthetic frame the generator used.
    const rgba = new Uint8ClampedArray(size * size * 4);
    const box = padBox(fixture.bbox, fixture.frame);
    for (let oy = 0; oy < size; oy++) {
      const sy = Math.min(H - 1, Math.floor(box.originY + ((oy + 0.5) * box.height) / size));
      for (let ox = 0; ox < size; ox++) {
        const sx = Math.min(W - 1, Math.floor(box.originX + ((ox + 0.5) * box.width) / size));
        const i = (oy * size + ox) * 4;
        rgba[i] = (sx * 6) % 256;
        rgba[i + 1] = (sy * 8) % 256;
        rgba[i + 2] = ((sx + sy) * 4) % 256;
        rgba[i + 3] = 255;
      }
    }

    const chw = normalizeRgbaToChwFloat32(rgba);
    const plane = size * size;

    for (const s of fixture.samples) {
      const got = chw[s.c * plane + s.y * size + s.x];
      expect(got).toBeCloseTo(s.v, 4);
    }

    const mean = chw.reduce((a, v) => a + v, 0) / chw.length;
    expect(mean).toBeCloseTo(fixture.expectedMean, 3);
  });

  it("keeps the ImageNet constants the trained weights expect", () => {
    expect(PREPROCESS_CONTRACT.mean).toEqual([0.485, 0.456, 0.406]);
    expect(PREPROCESS_CONTRACT.std).toEqual([0.229, 0.224, 0.225]);
    expect(PREPROCESS_CONTRACT.channelOrder).toBe("RGB");
  });
});
